In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## import data set

In [2]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IC-Assignment1/HRDataset_v14.csv')

## Analyze Data set

In [3]:
data.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,"Adinolfi, Wilson K",10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,"Ait Sidi, Karthikeyan",10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,"Akinkuolie, Sarah",10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,"Alagbe,Trina",10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,"Anderson, Carol",10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [4]:
data.describe()

,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,Termd,PositionID,Zip,ManagerID,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences
count,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,311.000000,303.000000,311.000000,311.000000,311.000000,311.000000,311.000000
mean,10156.000000,0.398714,0.810289,0.434084,2.392283,4.610932,2.977492,0.093248,69020.684887,0.334405,16.845659,6555.482315,14.570957,4.110000,3.890675,1.218650,0.414791,10.237942
std,89.922189,0.490423,0.943239,0.496435,1.794383,1.083487,0.587072,0.291248,25156.636930,0.472542,6.223419,16908.396884,8.078306,0.789938,0.909241,2.349421,1.294519,5.852596
min,10001.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,45046.000000,0.000000,1.000000,1013.000000,1.000000,1.120000,1.000000,0.000000,0.000000,1.000000
25%,10078.500000,0.000000,0.000000,0.000000,1.000000,5.000000,3.000000,0.000000,55501.500000,0.000000,18.000000,1901.500000,10.000000,3.690000,3.000000,0.000000,0.000000,5.000000
50%,10156.000000,0.000000,1.000000,0.000000,1.000000,5.000000,3.000000,0.000000,62810.000000,0.000000,19.000000,2132.000000,15.000000,4.280000,4.000000,0.000000,0.000000,10.000000
75%,10233.500000,1.000000,1.000000,1.000000,5.000000,5.000000,3.000000,0.000000,72036.000000,1.000000,20.000000,2355.000000,19.000000,4.700000,5.000000,0.000000,0.000000,15.000000
max,10311.000000,1.000000,4.000000,1.000000,5.000000,6.000000,4.000000,1.000000,250000.000000,1.000000,30.000000,98052.000000,39.000000,5.000000,5.000000,8.000000,6.000000,20.000000

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               311 non-null    object
 1   EmpID                       311 non-null    int64
 2   MarriedID                   311 non-null    int64
 3   MaritalStatusID             311 non-null    int64
 4   GenderID                    311 non-null    int64
 5   EmpStatusID                 311 non-null    int64
 6   DeptID                      311 non-null    int64
 7   PerfScoreID                 311 non-null    int64
 8   FromDiversityJobFairID      311 non-null    int64
 9   Salary                      311 non-null    int64
 10  Termd                       311 non-null    int64
 11  PositionID                  311 non-null    int64
 12  Position                    311 non-null    object
 13  State                       311 non-null    object
 14  Zip                         311 non-null    int64
 15  DOB                         311 non-null    object
 16  Sex                         311 non-null    object
 17  MaritalDesc                 311 non-null    object
 18  CitizenDesc                 311 non-null    object
 19  HispanicLatino              311 non-null    object
 20  RaceDesc                    311 non-null    object
 21  DateofHire                  311 non-null    object
 22  DateofTermination           104 non-null    object
 23  TermReason                  311 non-null    object
 24  EmploymentStatus            311 non-null    object
 25  Department                  311 non-null    object
 26  ManagerName                 311 non-null    object
 27  ManagerID                   303 non-null    float64
 28  RecruitmentSource           311 non-null    object
 29  PerformanceScore            311 non-null    object
 30  EngagementSurvey            311 non-null    float64
 31  EmpSatisfaction             311 non-null    int64
 32  SpecialProjectsCount        311 non-null    int64
 33  LastPerformanceReview_Date  311 non-null    object
 34  DaysLateLast30              311 non-null    int64
 35  Absences                    311 non-null    int64
dtypes: float64(2), int64(16), object(18)
memory usage: 87.6+ KB

## Check missing values

In [6]:
data.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Sex                             0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             207
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

In [7]:
data = data.drop(['ManagerID', 'EmpID', 'MarriedID', 'MaritalStatusID', 'EmpStatusID', 'DeptID','PerfScoreID','FromDiversityJobFairID','Employee_Name', 'ManagerName', 'DateofTermination', 'DOB', 'LastPerformanceReview_Date'], axis=1)

In [8]:
data.columns

Index(['GenderID', 'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip',
       'Sex', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'TermReason', 'EmploymentStatus', 'Department',
       'RecruitmentSource', 'PerformanceScore', 'EngagementSurvey',
       'EmpSatisfaction', 'SpecialProjectsCount', 'DaysLateLast30',
       'Absences'],
      dtype='object')

In [9]:
data=pd.get_dummies(data[data.columns], drop_first=True)

In [10]:
data.head()

,GenderID,Salary,Termd,PositionID,Zip,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,DaysLateLast30,Absences,...,RecruitmentSource_Employee Referral,RecruitmentSource_Google Search,RecruitmentSource_Indeed,RecruitmentSource_LinkedIn,RecruitmentSource_On-line Web application,RecruitmentSource_Other,RecruitmentSource_Website,PerformanceScore_Fully Meets,PerformanceScore_Needs Improvement,PerformanceScore_PIP
0,1,62506,0,19,1960,4.60,5,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1,1,104437,1,27,2148,4.96,3,6,0,17,...,0,0,1,0,0,0,0,1,0,0
2,0,64955,1,20,1810,3.02,3,0,0,3,...,0,0,0,1,0,0,0,1,0,0
3,0,64991,0,19,1886,4.84,5,0,0,15,...,0,0,1,0,0,0,0,1,0,0
4,0,50825,1,19,2169,5.00,4,0,0,2,...,0,1,0,0,0,0,0,1,0,0

## correlation

## Split the Data

In [11]:
X=data.drop(['Salary'],axis=1)
y=data[['Salary']]

## TRAIN TEST SPLIT

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
sc_y=StandardScaler()

In [14]:
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit(X_test)

In [15]:
print(X_train)
print('X_test -> ',X_test)

[[ 1.13855009 -0.70283419 -0.4948466  ...  0.55872114 -0.2445998
  -0.23520023]
 [ 1.13855009  1.42281068  0.33212077 ...  0.55872114 -0.2445998
  -0.23520023]
 [ 1.13855009  1.42281068  0.49751424 ...  0.55872114 -0.2445998
  -0.23520023]
 ...
 [-0.87831007 -0.70283419  0.33212077 ... -1.78980162 -0.2445998
  -0.23520023]
 [-0.87831007 -0.70283419 -2.31417482 ...  0.55872114 -0.2445998
  -0.23520023]
 [-0.87831007 -0.70283419  0.33212077 ...  0.55872114 -0.2445998
  -0.23520023]]
X_test ->  StandardScaler()

In [16]:
y_train=sc_y.fit_transform(y_train)
y_test=sc_y.transform(y_test)

In [17]:
print('y_train -> ',y_train)
print('y_test -> ',y_test)

y_train ->  [[ 2.63990036e-01]
 [-9.06123446e-01]
 [-5.27144353e-01]
 [-1.90950550e-01]
 [ 2.85072042e-01]
 [ 2.87330685e-02]
 [ 9.95026209e-01]
 [-2.21517388e-01]
 [ 1.13299117e+00]
 [-5.38037413e-01]
 [-1.24970911e-01]
 [-2.23464057e-01]
 [-4.15521549e-01]
 [-2.03955953e-01]
 [-7.38212928e-01]
 [-9.62411160e-01]
 [-8.65284825e-01]
 [-8.23907763e-01]
 [-2.58628346e-01]
 [ 1.54883271e+00]
 [ 3.98020237e-01]
 [-1.75957060e-01]
 [-2.67616157e-01]
 [ 1.36240813e+00]
 [-8.93095998e-02]
 [ 2.08116506e-01]
 [-5.03577238e-01]
 [-6.23566575e-01]
 [-2.96194908e-01]
 [-2.39865775e-01]
 [-4.11462538e-01]
 [-4.05166929e-01]
 [-3.75842645e-01]
 [-4.33704262e-01]
 [-5.64752333e-01]
 [ 9.02704417e-01]
 [ 8.93716607e-01]
 [ 1.28586678e+00]
 [-4.15438712e-01]
 [ 3.39568273e+00]
 [ 1.03921973e+00]
 [ 7.56187880e-02]
 [ 4.23275022e+00]
 [-1.79436213e-01]
 [-4.67728207e-02]
 [-2.79047657e-01]
 [-3.48465030e-01]
 [-6.26093102e-01]
 [-1.62785983e-01]
 [-2.27605905e-01]
 [ 5.98609936e-01]
 [-2.05115670e-01]
 [-6.68008604e-01]
 [ 1.72693217e+00]
 [ 1.94117060e-01]
 [ 4.54338882e+00]
 [-2.92550082e-01]
 [-7.61490113e-01]
 [ 1.28292606e+00]
 [-7.09197946e-02]
 [-9.47334834e-01]
 [-2.58462673e-01]
 [ 7.97708570e-01]
 [-6.49141150e-02]
 [-9.99127307e-02]
 [ 5.05584030e-01]
 [-6.42701912e-01]
 [-6.50530005e-01]
 [ 2.63575851e-01]
 [-2.58338417e-01]
 [-1.99938360e-01]
 [-6.40299641e-01]
 [-8.51368215e-01]
 [-2.45208759e-01]
 [-8.89183288e-01]
 [ 2.45498020e-02]
 [-9.48908736e-01]
 [-7.88991984e-01]
 [ 3.19904984e-01]
 [-4.95624890e-01]
 [ 7.41752204e-01]
 [-2.33860095e-01]
 [-1.38100569e-01]
 [-1.38763265e-01]
 [-8.29209328e-01]
 [-2.01926447e-01]
 [-5.22588320e-01]
 [ 1.27215726e+00]
 [-8.82390657e-01]
 [-2.19612138e-01]
 [-8.54356358e-03]
 [-9.09975365e-01]
 [-2.19736394e-01]
 [-4.74584302e-01]
 [-1.83370968e-01]
 [-2.79586097e-01]
 [ 1.89256467e+00]
 [-1.47751075e-01]
 [-5.33481380e-01]
 [-1.91488990e-01]
 [ 1.14375997e+00]
 [-5.21180092e-01]
 [-6.31436086e-01]
 [-3.80274423e-01]
 [-3.65860791e-01]
 [-9.18880338e-01]
 [ 9.94984791e-01]
 [ 3.88783916e-01]
 [-6.13543302e-01]
 [-6.84575996e-01]
 [-3.25933377e-01]
 [ 8.08518793e-01]
 [ 4.62622578e+00]
 [ 1.54833569e+00]
 [-7.42727542e-01]
 [ 7.79382229e-02]
 [ 2.45227464e-01]
 [ 4.21332829e-03]
 [-8.93283717e-01]
 [-2.75402831e-01]
 [-4.37266251e-01]
 [-2.72379282e-01]
 [-5.10582973e-03]
 [ 1.57645883e+00]
 [ 9.11921365e-02]
 [-3.14004854e-01]
 [-1.98405876e-01]
 [-2.40197123e-01]
 [-4.11503957e-01]
 [-1.61874777e-01]
 [-6.65026473e-01]
 [ 1.57420286e-01]
 [-8.42628916e-01]
 [-6.95841822e-01]
 [-4.42462934e-02]
 [-4.36664347e-02]
 [ 1.79537755e-01]
 [ 6.92629886e-01]
 [ 7.52551939e+00]
 [ 8.37553148e-01]
 [ 1.02666993e+00]
 [-6.78653153e-01]
 [-8.73692776e-01]
 [-8.19765915e-01]
 [-8.20511448e-01]
 [ 1.61396460e-01]
 [ 2.48789453e-01]
 [-9.60505910e-01]
 [-7.24006389e-01]
 [-5.58208213e-01]
 [ 2.49369312e-01]
 [ 1.04576385e+00]
 [ 5.49984641e-01]
 [-1.48330934e-01]
 [ 2.88923961e-01]
 [-6.79150175e-01]
 [-4.44100300e-01]
 [-3.32808844e-01]
 [-1.37106526e-01]
 [ 9.27660388e-02]
 [-5.45285647e-01]
 [-8.47764808e-01]
 [ 1.18103660e+00]
 [ 1.02236241e+00]
 [-4.68620041e-01]
 [-3.28252812e-01]
 [-4.27864256e-01]
 [ 1.03135022e+00]
 [ 1.47231340e-01]
 [-1.68128967e-01]
 [ 1.32997746e+00]
 [-9.23933392e-01]
 [-8.96762869e-01]
 [-7.72154036e-02]
 [-2.87869793e-01]
 [-6.33175662e-01]
 [-8.04233985e-01]
 [-2.85094755e-01]
 [-2.17624051e-01]
 [ 1.68497525e+00]
 [ 1.31403134e+00]
 [-6.71736267e-01]
 [-4.24260848e-01]
 [-2.43552020e-01]
 [-8.96348685e-01]
 [-6.54423342e-01]
 [-1.44520434e-01]
 [-5.11115401e-01]
 [-2.18700932e-01]
 [ 6.23668117e-01]
 [-2.18700932e-01]
 [-6.34583890e-01]
 [-2.62728776e-01]
 [-5.82686535e-01]
 [-4.28734044e-01]
 [ 3.67360074e+00]
 [-5.51084234e-01]
 [-5.53859273e-01]
 [-3.79446053e-01]
 [ 1.49652117e+00]
 [-1.75584294e-01]
 [-3.41092540e-01]
 [-6.47423619e-01]
 [-2.54445080e-01]
 [-1.77448125e-01]
 [-6.18762031e-01]
 [-2.15263198e-01]
 [-1.07326639e-01]
 [-3.18022447e-01]
 [-3.97463092e-01]
 [-9.95399644e-02]
 [-3.75552716e-01]
 [ 8.95768158e-02]
 [-3.25519192e-01]
 [ 4.28567702e-02]
 [ 6.87452576e-01]
 [ 3.00759158e+00]
 [-1.05316506e-02]
 [-3.70126895e-01]
 [-8.64456455e-01]
 [-4.18255169e-01]
 [ 8.69238285e-01]
 [ 6.36259335e-01]
 [-2.01098078e-01]
 [-5.03494401e-01]
 [ 1.54377364e-02]
 [-7.40449526e-01]
 [-7.27112775e-01]
 [-1.40254330e-01]
 [-1.56780304e-01]
 [-3.12762300e-01]
 [ 1.72082428e-01]
 [-7.67578630e-01]
 [-3.16821311e-01]
 [-1.24059705e-01]
 [ 1.22986899e+00]
 [-5.92295622e-01]
 [-1.07616568e-01]
 [ 1.43752188e-01]
 [-6.10561172e-01]
 [ 1.40894313e-01]
 [-9.63363785e-01]
 [-7.14935742e-01]
 [-5.17949450e-01]
 [-7.06030769e-01]
 [-4.34491213e-01]
 [-3.39021616e-01]
 [-7.02800127e-01]]
y_test ->  StandardScaler()

## Random Search CV

In [18]:
from sklearn.linear_model import SGDRegressor, Ridge, LinearRegression
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor

In [19]:
model_params= {
    'SVR': {
        'model': SVR(gamma='auto'),
        'params': {
            'C': [0.1, 1, 10, 20, 100],
            'kernel': ['rbf', 'linear', 'poly']
        }
    },
    'SGD': {
        'model': SGDRegressor(max_iter=1000, tol=1e-3),
        'params': {
            'eta0': [0.01, 0.1, 1, 10, 100]
        }
    },
    'LinearRegression': {
        'model': LinearRegression(),
        'params': {}, ## no params
    },
    'Ridge': {
        'model': Ridge(),
        'params': {
            'alpha': [0.01, 0.1, 1, 10, 100, 200],
            'max_iter': [100, 500, 1000]
        }
    },
    'DecisionTree': {
        'model': DecisionTreeRegressor(max_depth=5),
        'params': {}
    },
}

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311 entries, 0 to 310
Columns: 218 entries, GenderID to PerformanceScore_PIP
dtypes: float64(1), int64(9), uint8(208)
memory usage: 87.6 KB

In [21]:
from sklearn.model_selection import RandomizedSearchCV
scores=[]
for model_name, model_parameter in model_params.items():
  clf=RandomizedSearchCV(model_parameter['model'], model_parameter['params'], cv=6, return_train_score=False)
  clf.fit(X_train, y_train)
  scores.append({
    'model': model_name,
    'best_score': clf.best_score_,
    'best_params': clf.best_params_
  })

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:296: UserWarning: The total space of parameters 5 is smaller than n_iter=10. Running 5 iterations. For exhaustive searches, use GridSearchCV.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [22]:
df=pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

              model    best_score                      best_params
0               SVR  3.080030e-01       {'kernel': 'rbf', 'C': 10}
1               SGD  3.548439e-01                   {'eta0': 0.01}
2  LinearRegression -6.269720e+27                               {}
3             Ridge  3.637828e-01  {'max_iter': 100, 'alpha': 100}
4      DecisionTree  4.720197e-01                               {}